### ISSUE TITLE
Write an article/tutorial to introduce the plugin

### ISSUE THREAD

**Issue by hsluoyz** [casbin-lua/apisix-authz#7]
On Medium or personal blog. You can refer to: https://casbin.org/docs/en/tutorials (like this one: https://ddtkey.com/blog/authz-mechanisms-in-Rust/)

We will put this article to the official site, and the apisix community will also help us spread it.

**Comment by hsluoyz** [comment]
@rushitote

**Comment by rushitote** [comment]
Sure, working on it.

**Comment by rushitote** [comment]
@hsluoyz I have written one [here](https://rushikeshtote.com/blog/apisix-casbin-authorization) and on [Medium](https://medium.com/@rushitote/authorization-in-apisix-using-casbin-59b693669d6d).

**Comment by hsluoyz** [comment]
@rushitote very good article! I have some suggestions to improve it:

1. Add some introduction about Casbin and APISIX communities.
2. How the two communities start to engage with each other, and the interactions between them (like issue, disucssion, PR, etc.)
3. What is the advantage to use this plugin, what problem it can solve.

Can you improve this part?

**Comment by rushitote** [comment]
@hsluoyz I have updated it [here](https://medium.com/@rushitote/authorization-in-apisix-using-casbin-59b693669d6d). Is this better?

**Comment by hsluoyz** [comment]
@rushitote it looks great! Thanks!

**Comment by hsluoyz** [comment]
@rushitote can you also put your article into our blog page: https://casbin.org/blog/ ? You can make a PR to casbin-website repo.

BTW, APISIX community is also putting the article into their website: https://github.com/apache/apisix-website/pull/475 but it's in Chinese. We will put an English version as you have written :)

I think this is really a good collaboration between the two communities. Kudos!

**Comment by rushitote** [comment]
@hsluoyz Wow, great to know that! I will create a PR in casbin-website: https://github.com/casbin/casbin-website/pull/266

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-website/pull/266
