### ISSUE TITLE
authz-casbin is missing from APISIX Plugin Hub

### ISSUE THREAD

**Issue by hsluoyz** [casbin-lua/apisix-authz#8]
The plugin `authz-casbin` is already in docs: https://apisix.apache.org/docs/apisix/plugins/authz-casbin/ , but it's missing from APISIX Plugin Hub: https://apisix.apache.org/plugins

We can add it.

**Comment by hsluoyz** [comment]
@rushitote @Edmond-J-A can you guys do this?

/cc @leeqvip

**Comment by rushitote** [comment]
Created a PR [here](https://github.com/apache/apisix-website/pull/877).

**Comment by hsluoyz** [comment]
@rushitote thanks! Done at: https://apisix.apache.org/plugins
